name: Build and Push Docker images

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: centos
            version: "7"
          - os: centos
            version: stream8
          - os: centos
            version: stream9
          - os: debian
            version: "10"
          - os: debian
            version: "11"
          - os: debian
            version: "12"
          - os: fedora
            version: "38"
          - os: fedora
            version: "39"
          - os: fedora
            version: "40"
          - os: fedora
            version: "41"
          - os: ubuntu
            version: "20.04"
          - os: ubuntu
            version: "22.04"
          - os: ubuntu
            version: "23.10"
          - os: ubuntu
            version: "24.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          tag="linux-vm:${{ matrix.os }}-${{ matrix.version }}"
          image="${{ secrets.DOCKERHUB_USERNAME }}/$tag"
          docker buildx build --push --tag "$image" dockerfiles/${{ matrix.os }}/${{ matrix.version }}
